CC=gcc
CFLAGS=-Wall -g -pedantic

all: zmodemFileReceive

zmodemFileReceive: zmodemFileReceive.c
	$(CC) $(CFLAGS) -o zmodemFileReceive zmodemFileReceive.c


clean:
	rm -f zmodemFileReceive

	
